- name: ensure ansible host apps installed redhat/centos
  yum:
    update_cache: yes
    state: latest
    name:
      - curl
      - htop
      - telnet
      - vim
      - net-tools
      - ncdu
      #- ffmpeg
      - iftop
      - iotop
      - openssh-server
      - ntp          
  become: yes
  when: enable_install_packages