#- name: Configure Docker default config file
#  template:
#      src: default_docker.j2
#      dest: /etc/default/docker
#      mode: 0644
#      owner: root
#      group: root
#      force: yes

#- name: restart docker
#  shell: service docker restart

- name: restart NetworkManager dispatcher
  service:
    name: NetworkManager-dispatcher
    enabled: yes
    state: restarted
  become: yes

- name: restart systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
    state: restarted
  become: yes

- name: reload services
  systemd:
    daemon_reload: yes